# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddrInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('dis', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=20)),
                ('detail_addr', models.CharField(max_length=30)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('is_delete', models.BooleanField(default=False)),
                ('default_addr', models.BooleanField(default=False)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '地址信息',
                'db_table': 'addrinfo',
            },
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_ares_info', to='index.AreaInfo')),
            ],
            options={
                'verbose_name_plural': '省市区',
                'db_table': 'areainfo',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30)),
                ('buy_count', models.IntegerField(default=1)),
                ('is_delete', models.BooleanField(default=False)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30)),
                ('goods_desc', models.CharField(max_length=80)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('goods_detail', tinymce.models.HTMLField()),
                ('img_path', models.ImageField(upload_to='static/uploads/')),
                ('sale_count', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('comment_date', models.DateTimeField()),
                ('comment', tinymce.models.HTMLField()),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_comments', to='index.Goods')),
            ],
            options={
                'verbose_name_plural': '商品评论',
                'db_table': 'goodscomment',
            },
        ),
        migrations.CreateModel(
            name='GoodSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_name', models.CharField(max_length=10)),
                ('sort_pic', models.ImageField(upload_to='static/uploads/')),
                ('sort_class', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '商品种类',
                'db_table': 'goodsort',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('buy_count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_order', to='index.Goods')),
            ],
            options={
                'verbose_name_plural': '订单详细',
                'db_table': 'orderdetail',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finish', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('order_time', models.DateTimeField()),
                ('order_number', models.CharField(blank=True, max_length=20, null=True)),
                ('addr', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '订单',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='RecentSee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '最近浏览',
                'db_table': 'recentsee',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('addr', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='recentsee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recent_see', to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_order', to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='index.Orders'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodSort'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='addrinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addr_info', to='index.UserInfo'),
        ),
    ]
