# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_goods_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
