# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20170420_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recent_see', to='index.UserInfo'),
        ),
    ]
