# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20170421_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addr_info', to='index.UserInfo'),
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_ares_info', to='index.AreaInfo'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='index.UserInfo'),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_comments', to='index.Goods'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_order', to='index.Goods'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='index.Orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_order', to='index.UserInfo'),
        ),
    ]
