# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20170421_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_cart', to='index.UserInfo'),
        ),
    ]
