# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20170421_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='addr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
